name: "Check CI result"

runs:
  using: composite
  steps:
    - if: github.event.workflow_run.event == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          return await require('./${{ github.action_path }}/script.js')({ github, context })
        result-encoding: string
        github-token: ${{ github.token }}
