name: "Check CI result"

on:
  workflow_run:
    types: [completed]
    workflows: ["*"]
  pull_request_review:
    types: [submitted]
permissions:
  checks: write
  statuses: write
jobs:
  check:
    if: github.event.workflow_run.event == 'pull_request' || github.event_name == 'pull_request_review'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/check-ci-result
