on:
  workflow_run:
    types: [completed]
    workflows: ["*"]
jobs:
  check:
    if: toJson(github.event.workflow_run.pull_requests) != '[]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "${{ toJson(github) }}"
      - uses: actions/github-script@v7
        with:
          script: |
            return await require('./.github/workflows/script.js')({ github, context })
          result-encoding: string
          github-token: ${{ secrets.GITHUB_TOKEN }}
