name: No Failed CI Gatekeeper

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_run:
    workflows: ["*"]
    types: [completed]
  pull_request_review:
    types: [submitted]

permissions:
  statuses: write

jobs:
  run-gatekeeper:
    runs-on: ubuntu-latest
    steps:
      - uses: mtsmfm/no-failed-ci-gatekeeper@ai-wip
